version: '3.8'

services:
  {{PROJECT_NAME}}_backend:
    build:
      context: ./.docker/backend
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: {{PROJECT_NAME}}_backend
    restart: unless-stopped
    volumes:
      - ./src:/var/www/{{PROJECT_NAME}}/
      - ./.docker/backend/apache-default.conf:/etc/apache2/sites-available/000-default.conf
    working_dir: /var/www/{{PROJECT_NAME}}/
    networks:
      - {{PROJECT_NAME}}_network

# docker-compose down -v --rmi all --remove-orphans
